# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        language_version: python3

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        args: [--line-length=79]

# -   repo: https://github.com/PyCQA/flake8
#     rev: 4.0.1
#     hooks:
#     -   id: flake8
#         args: [--max-line-length=79]

# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: v2.6.0
#     hooks:
#     -   id: reorder-python-imports
#         args: [--py36-plus, --application-directories=tests, --separate, --diff-only]

# -   repo: https://github.com/asottile/pyupgrade
#     rev: v2.26.0
#     hooks:
#     -   id: pyupgrade
#         args: [--py36-plus, --py38-plus, --py39-plus, --py310-plus]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.910
#     hooks:
#     -   id: mypy
#         files: ^src/.*\.py$
#         args: []
