[book]
authors = ["Chad B. Hovey <chovey@sandia.gov>", "Michael R. Buche <mrbuche@sandia.gov>"]
description = "Automatic figure generation."
language = "en"
multilingual = false
src = "book/"
title = "figio"

[build]
build-dir = "book/build/"
create-missing = false

[rust]
edition = "2021"

[preprocessor.cmdrun]

[preprocessor.katex]
after = ["links"]
