[book]
authors = ["Chad B. Hovey <chovey@sandia.gov>", "Michael R. Buche <mrbuche@sandia.gov>"]
description = "Automatic figure generation."
language = "en"
multilingual = false
src = "src"
title = "figio"

[rust]
edition = "2021"

[preprocessor.cmdrun]

[preprocessor.katex]
after = ["links"]
