name: Book_v3
on:
  pull_request:
    branches: main
  push:
    branches: main
env:
  CARGO_TERM_COLOR: always
jobs:
  mdbook:
    runs-on: ubuntu-latest
    container:
        image: rust:latest # Cargo/Rust is needed to build mdbook and its preprocessors
    steps:
      - name: checkout
        uses: actions/checkout@v4

    # Install mdBook and Preprocessors directly using Cargo
    # Replaces 'cargo install mdbook'
      - name: Install mdBook and Preprocessors
        run: cargo install mdbook mdbook-cmdrun mdbook-katex

    # Setup Python environment since the book uses it to build examples
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: pip install -e .[dev]

    # Build and Artifact Upload
      - name: build mdBook
        run: mdbook build

    # Q: Why this step?
    # A: The 'move' step in the previous version copied the built book to a different
    #    directory (_site/) which is unnecessary. The 'actions/upload-pages-artifact@v3'
    #    action can upload the 'book/' directory directly. So we remove the 'move' step.
    #   - name: move
    #     run: mkdir -p _site/ && cp -r book/build/* _site/

    # The 'mdbook build' output is in the default 'book/' directory.
    # The 'actions/upload-pages-artifact@v3' action can upload 'book/' directly.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: book/

  deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: mdbook
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
